[build]
  command = "npm run build"
  publish = "dist/user-management-app/browser"

# Redirigir todas las rutas a index.html para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración del entorno de construcción
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
